# Generated by Django 4.2.5 on 2023-09-19 02:14

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='funcionario',
            name='arma_puno',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='camara',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='camara_relacion',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='carabina_lanza_gases',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='carabina_lanza_gases_relacion',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='escopeta',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='escopeta_relacion',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='extra',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='fecha_registro',
        ),
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_registro', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('servicio', models.TextField(max_length=100)),
                ('camara', models.BooleanField(default=False)),
                ('escopeta', models.BooleanField(default=False)),
                ('carabina_lanza_gases', models.BooleanField(default=False)),
                ('extra', models.TextField(max_length=200)),
                ('arma_puno', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='inventario.armapuño')),
                ('camara_relacion', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventario.camara')),
                ('carabina_lanza_gases_relacion', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventario.carabinalanzagases')),
                ('escopeta_relacion', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventario.escopeta')),
            ],
        ),
    ]
