# Generated by Django 4.2.5 on 2023-09-19 02:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_remove_funcionario_arma_puno_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registro',
            name='funcionario',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='inventario.funcionario'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='grado',
            field=models.CharField(choices=[('Carabinero', 'Carabinero'), ('Cabo 2', 'Cabo 2'), ('Cabo 1', 'Cabo 1'), ('Sargento 2', 'Sargento 2'), ('Sargento 1', 'Sargento 1'), ('Suboficial', 'Suboficial'), ('Suboficial Mayor', 'Suboficial Mayor'), ('Subteniente', 'Subteniente'), ('Teniente', 'Teniente'), ('Capitán', 'Capitán'), ('Mayor', 'Mayor'), ('Teniente Coronel', 'Teniente Coronel'), ('Coronel', 'Coronel')], default='1', max_length=20),
        ),
    ]
