# Generated by Django 4.2.5 on 2023-09-19 02:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0004_remove_armapuño_nombre_armapuño_tipo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='armapuño',
            name='calibre',
        ),
    ]
