# Generated by Django 4.2.5 on 2023-09-19 02:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0005_remove_armapuño_calibre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registro',
            name='extra',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='registro',
            name='funcionario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.funcionario'),
        ),
    ]
