# Generated by Django 4.2.5 on 2023-10-04 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0006_alter_registro_extra_alter_registro_funcionario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='camara',
            name='nombre',
        ),
        migrations.RemoveField(
            model_name='carabinalanzagases',
            name='nombre',
        ),
        migrations.RemoveField(
            model_name='carabinalanzagases',
            name='tipo',
        ),
        migrations.RemoveField(
            model_name='escopeta',
            name='nombre',
        ),
        migrations.RemoveField(
            model_name='escopeta',
            name='tipo',
        ),
        migrations.AddField(
            model_name='camara',
            name='modelo',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='carabinalanzagases',
            name='marca',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='carabinalanzagases',
            name='modelo',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='escopeta',
            name='marca',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='escopeta',
            name='modelo',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='camara',
            name='resolucion',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
