# Generated by Django 4.2.5 on 2023-10-07 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0008_alter_registro_fecha_registro'),
    ]

    operations = [
        migrations.AddField(
            model_name='registro',
            name='finalizado',
            field=models.BooleanField(default=False),
        ),
        migrations.RemoveField(
            model_name='registro',
            name='arma_puno',
        ),
        migrations.RemoveField(
            model_name='registro',
            name='camara_relacion',
        ),
        migrations.RemoveField(
            model_name='registro',
            name='carabina_lanza_gases_relacion',
        ),
        migrations.RemoveField(
            model_name='registro',
            name='escopeta_relacion',
        ),
        migrations.RemoveField(
            model_name='registro',
            name='funcionario',
        ),
        migrations.AddField(
            model_name='registro',
            name='arma_puno',
            field=models.ManyToManyField(to='inventario.armapuño'),
        ),
        migrations.AddField(
            model_name='registro',
            name='camara_relacion',
            field=models.ManyToManyField(blank=True, null=True, to='inventario.camara'),
        ),
        migrations.AddField(
            model_name='registro',
            name='carabina_lanza_gases_relacion',
            field=models.ManyToManyField(blank=True, null=True, to='inventario.carabinalanzagases'),
        ),
        migrations.AddField(
            model_name='registro',
            name='escopeta_relacion',
            field=models.ManyToManyField(blank=True, null=True, to='inventario.escopeta'),
        ),
        migrations.AddField(
            model_name='registro',
            name='funcionario',
            field=models.ManyToManyField(to='inventario.funcionario'),
        ),
    ]
