# Generated by Django 4.2.5 on 2023-10-07 19:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0009_registro_finalizado_remove_registro_arma_puno_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registro',
            name='camara_relacion',
            field=models.ManyToManyField(blank=True, to='inventario.camara'),
        ),
        migrations.AlterField(
            model_name='registro',
            name='carabina_lanza_gases_relacion',
            field=models.ManyToManyField(blank=True, to='inventario.carabinalanzagases'),
        ),
        migrations.AlterField(
            model_name='registro',
            name='escopeta_relacion',
            field=models.ManyToManyField(blank=True, to='inventario.escopeta'),
        ),
        migrations.AlterField(
            model_name='registro',
            name='extra',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='registro',
            name='fecha_registro',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
    ]
