# Generated by Django 4.2.5 on 2023-10-07 19:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0010_alter_registro_camara_relacion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registro',
            name='arma_puno',
        ),
        migrations.RemoveField(
            model_name='registro',
            name='camara_relacion',
        ),
        migrations.RemoveField(
            model_name='registro',
            name='carabina_lanza_gases_relacion',
        ),
        migrations.RemoveField(
            model_name='registro',
            name='escopeta_relacion',
        ),
        migrations.RemoveField(
            model_name='registro',
            name='funcionario',
        ),
        migrations.AddField(
            model_name='registro',
            name='arma_puno',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='inventario.armapuño'),
        ),
        migrations.AddField(
            model_name='registro',
            name='camara_relacion',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventario.camara'),
        ),
        migrations.AddField(
            model_name='registro',
            name='carabina_lanza_gases_relacion',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventario.carabinalanzagases'),
        ),
        migrations.AddField(
            model_name='registro',
            name='escopeta_relacion',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventario.escopeta'),
        ),
        migrations.AddField(
            model_name='registro',
            name='funcionario',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='inventario.funcionario'),
        ),
    ]
